apiVersion: v1
kind: Pod
metadata:
  name: app-neighborfood
  labels:
    app: app-service
spec:
  containers:
    - name: neighborfood-app-container
      image: migprogrammer/neighborfood-v2:v4
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: app-neighborfood-configmap
